name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.13'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Install Railway
        run: npm install -g @railway/cli

      - name: Link Service
        run: railway link 69a2367a-d3a8-419a-a0f5-bbe5b902aa74
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy to Railway
        run:  railway up 
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

